Repository OpenIPSL/OpenIPSL, pull requests merged in 2020-10, with the labels that each got.

#211 Fixing the machine models
  OpenIPSL/Electrical/Controls/PSSE/PSS/PSS2A.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/PSS2B.mo
  OpenIPSL/Electrical/Machines/PSSE/GENCLS.mo
  OpenIPSL/Electrical/Machines/PSSE/GENSAE.mo
  OpenIPSL/Electrical/Machines/PSSE/Plant.mo
  OpenIPSL/Examples/Controls/PSSE/ES/EXAC1.mo
  OpenIPSL/Examples/Controls/PSSE/ES/IEEET2.mo
  OpenIPSL/Examples/Controls/PSSE/PSS/STAB3.mo
  OpenIPSL/Examples/Controls/PSSE/PSS/STABNI.mo
  OpenIPSL/Examples/Controls/PSSE/TG/GAST.mo
  OpenIPSL/Examples/Controls/PSSE/TG/GGOV.mo
  OpenIPSL/Examples/Controls/PSSE/TG/HYGOV.mo
  OpenIPSL/Examples/Controls/PSSE/TG/IEEEG1.mo
  OpenIPSL/Examples/Controls/PSSE/TG/IEESGO.mo
  OpenIPSL/Examples/Controls/PSSE/TG/TGOV1.mo
  OpenIPSL/Examples/Controls/PSSE/TG/package.order
  OpenIPSL/Examples/Machines/PSSE/GENCLS.mo
  OpenIPSL/Examples/Machines/PSSE/package.order
  OpenIPSL/NonElectrical/Continuous/RampTrackingFilter.mo
Labels: bug

#215 Fixing governor models
  OpenIPSL/Electrical/Controls/PSAT/TG/TGTypeI.mo
  OpenIPSL/Electrical/Controls/PSAT/TG/TGTypeIII.mo
  OpenIPSL/Electrical/Controls/PSAT/TG/TGTypeIV.mo
  OpenIPSL/Electrical/Controls/PSAT/TG/TGTypeV.mo
  OpenIPSL/Electrical/Controls/PSAT/TG/TGTypeVI.mo
  OpenIPSL/Electrical/Controls/PSAT/TG/TGtypeII.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/GAST.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/GGOV1/GGOV1.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/HYGOV.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/IEEEG1.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/IEESGO.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/TGOV1.mo
  OpenIPSL/Examples/Controls/CGMES/ES/ExcSEXS.mo
  OpenIPSL/Examples/Controls/CGMES/ES/package.mo
  OpenIPSL/Examples/Controls/CGMES/package.mo
  OpenIPSL/Examples/Controls/PSSE/TG/GAST.mo
Labels: bug

#213 Fix Banks models
  OpenIPSL/Examples/SMIBpartial2.mo
Labels: bug

#212 Fix exciter models
  OpenIPSL/Examples/Controls/PSSE/ES/IEEET2.mo
Labels: bug

#222 Sorting the examples and excitation models alphabetical
  OpenIPSL/Electrical/Controls/PSSE/ES/package.order
  OpenIPSL/Electrical/Controls/PSSE/TG/package.order
  OpenIPSL/Examples/Controls/PSSE/ES/package.order
  OpenIPSL/Examples/Controls/PSSE/PSS/package.order
  OpenIPSL/Examples/Controls/PSSE/TG/package.order
  OpenIPSL/Examples/Machines/PSSE/package.order
Labels: Cleanup

#225 Remove SMIBpartial2 and instead update SMIBpartial
  OpenIPSL/Examples/Banks/PSSE/CSVGN1.mo
  OpenIPSL/Examples/SMIBpartial.mo
  OpenIPSL/Examples/SMIBpartial2.mo
  OpenIPSL/Examples/package.order
Labels: Cleanup

#230 Correct calculation of I_T in ESSTB4
  OpenIPSL/Electrical/Controls/PSSE/ES/ESST4B.mo
Labels: bug, hacktoberfest-accepted

#233 Explains the PSAT AVR models mix up
  OpenIPSL/Electrical/Controls/PSAT/AVR/AVRTypeI.mo
  OpenIPSL/Electrical/Controls/PSAT/AVR/AVRTypeII.mo
  OpenIPSL/Electrical/Controls/PSAT/AVR/AVRtypeIII.mo
  OpenIPSL/UsersGuide/References.mo
Labels: Cleanup, DOC

#224 Fix the CI setup
  .travis.yml
  CI/CITests.py
  CI/syntaxCheck.py
  Dockerfile
Labels: CI

#236 Better implementation of PSTransformer
  OpenIPSL/Electrical/Branches/PSAT/PhaseShiftingTransformer.mo
  OpenIPSL/Electrical/Branches/PSAT/PhaseShiftingTransformer/PSTransformer.mo
  OpenIPSL/Electrical/Branches/PSAT/PhaseShiftingTransformer/package.mo
  OpenIPSL/Electrical/Branches/PSAT/PhaseShiftingTransformer/package.order
  OpenIPSL/Electrical/Branches/PSAT/PhaseShiftingTransformer/pst1.mo
  OpenIPSL/Electrical/Branches/PSAT/PhaseShiftingTransformer/pst2.mo
  OpenIPSL/Electrical/Branches/PSAT/TwoWindingTransformer.mo
  OpenIPSL/Electrical/Branches/PSAT/package.order
  OpenIPSL/Examples/Branches/PSAT/PhaseShiftingTransformer_Test.mo
  OpenIPSL/UsersGuide/References.mo
Labels: bug, enhancement

#237 Sort classes in alphabetical order when appropriate
  OpenIPSL/Electrical/Branches/PSSE/TwoWindingTransformer.mo
  OpenIPSL/Electrical/Essentials/package.mo
  OpenIPSL/Electrical/Sensors/package.mo
  OpenIPSL/Electrical/package.order
  OpenIPSL/Examples/Branches/PSSE/TwoWindingTransformer.mo
  OpenIPSL/Examples/Branches/PSSE/package.mo
  OpenIPSL/Examples/Branches/PSSE/package.order
  OpenIPSL/Examples/Branches/package.order
  OpenIPSL/Examples/Controls/package.order
  OpenIPSL/Examples/Machines/package.order
  OpenIPSL/Examples/TwoWindingTransformer.mo
  OpenIPSL/Examples/Wind/GE/WT_Test.mo
  OpenIPSL/Examples/Wind/GE/package.mo
  OpenIPSL/Examples/Wind/GE/package.order
  OpenIPSL/Examples/Wind/GE_WT_Test.mo
  OpenIPSL/Examples/Wind/PSAT/WT_Test.mo
  OpenIPSL/Examples/Wind/PSAT/package.mo
  OpenIPSL/Examples/Wind/PSAT/package.order
  OpenIPSL/Examples/Wind/PSAT_WT_Test.mo
  OpenIPSL/Examples/Wind/package.order
  OpenIPSL/Examples/package.order
  OpenIPSL/NonElectrical/Functions/package.mo
  OpenIPSL/NonElectrical/package.order
Labels: Cleanup

#240 Fix gencls
  OpenIPSL/Electrical/Buses/Bus.mo
  OpenIPSL/Electrical/Machines/PSSE/GENCLS.mo
  OpenIPSL/Examples/BaseClasses/SMIB.mo
Labels: OMrelated, bug

#241 Add an initial speed deviation and remove superfluous initial equationns
  OpenIPSL/Electrical/Machines/PSSE/BaseClasses/baseMachine.mo
  OpenIPSL/Electrical/Machines/PSSE/GENROE.mo
  OpenIPSL/Electrical/Machines/PSSE/GENROU.mo
  OpenIPSL/Electrical/Machines/PSSE/GENSAE.mo
  OpenIPSL/Electrical/Machines/PSSE/GENSAL.mo
Labels: Cleanup, enhancement

#242 Cleans up the PSS and ES models
  OpenIPSL/Electrical/Controls/CGMES/ES/ExcSEXS.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/ConstantExcitation.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/ESAC1A.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/ESAC2A.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/ESDC1A.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/ESDC2A.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/ESST1A.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/ESST4B.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/EXAC1.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/EXAC2.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/EXNI.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/EXST1.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/IEEET1.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/IEEET2.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/SCRX.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/SEXS.mo
  OpenIPSL/Electrical/Controls/PSSE/ES/ST5B.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/BaseClasses/BasePSS.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/DisabledPSS.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/IEE2ST.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/IEEEST.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/PSS2A.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/PSS2B.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/STAB2A.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/STAB3.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/STABNI.mo
  OpenIPSL/Electrical/Controls/PSSE/PSS/STBSVC.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/BaseClasses/BaseGovernor.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/ConstantPower.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/GAST.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/HYGOV.mo
  OpenIPSL/Electrical/Controls/PSSE/TG/IEEEG1.mo
  OpenIPSL/Examples/Controls/PSSE/PSS/IEEEST.mo
  OpenIPSL/Examples/Controls/PSSE/PSS/PSS2A.mo
  OpenIPSL/Examples/Controls/PSSE/PSS/PSS2B.mo
  OpenIPSL/Examples/Controls/PSSE/PSS/STAB3.mo
  OpenIPSL/Examples/Controls/PSSE/PSS/STABNI.mo
  OpenIPSL/Examples/Controls/PSSE/PSS/package.order
  OpenIPSL/Examples/Controls/PSSE/TG/package.order
  OpenIPSL/UsersGuide/References.mo
Labels: Cleanup
